# Site
name: "Touch My Fish"
title: "Touch My Fish"
description: "çƒ­çˆ±æŠ€æœ¯çš„å°ä¼™ä¼´é›†ç»“åœ°ï¼Œä¸€èµ·åˆ†äº«æŠ€æœ¯ï¼Œä¸€èµ·æ‘¸é±¼å§ğŸŸ"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-126817847-3'
comment_gitalk_clientId: 'c00c8118274d907f3b2f'
comment_gitalk_clientSecret: 'f86b1824c258bfa65cfb0556e769a222b11e39ba'
comment_gitalk_repo: 'touchmyfish.com'
comment_gitalk_repo_owner: 'touchmyfish'
comment_gitalk_repo_admin: 'elfgzp'
include: 
  - _pages
exclude:
  - vendor
  - .gitignore
permalink: /:categories/:year/:month/:day/:title/

# Authors
authors:
  Sky:
    name: Sky
    display_name: Sky
    avatar: 'assets/images/avatar/sky.png'
    email: lecw199@163.com
    web: ''
    github: 'https://github.com/lecw199'
    description: "é”…ç›–å¤´"
  elfgzp:
    name: elfgzp
    display_name: elfgzp
    avatar: 'assets/images/avatar/elfgzp.jpeg'
    email: 741424975@qq.com
    web: 'https://elfgzp.cn'
    github: 'https://github.com/elfgzp'
    description: "ä¸€ä¸ªå…´è¶£ä½¿ç„¶çš„ç¨‹åºå‘˜ ğŸ±"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"
